name: Detect Binary Language

on:
  workflow_dispatch:

jobs:
  detect-language:
    runs-on: ubuntu-latest

    steps:
      - name: 下载二进制文件
        run: |
          curl -L -o s-box https://amd64.ssss.nyc.mn/s-box
          chmod +x s-box

      - name: 检测语言
        run: |
          BIN=s-box
          LANG="Unknown"

          echo "=== 文件信息 ==="
          file $BIN

          echo "=== 字符串分析 ==="
          STRINGS=$(strings $BIN)

          # JS/Node 检测
          if echo "$STRINGS" | grep -q "node:" && echo "$STRINGS" | grep -q "\.js"; then
              LANG="JavaScript/Node"
          # Python 打包检测
          elif echo "$STRINGS" | grep -qE "PyInit_|cpython"; then
              LANG="Python"
          # Go 检测
          elif echo "$STRINGS" | grep -qE "Go build ID|runtime.main|go.itab."; then
              LANG="Go"
          # Rust 检测
          elif echo "$STRINGS" | grep -qE "core::|std::|alloc::|__rust_"; then
              LANG="Rust"
          # C/C++ 检测
          elif echo "$STRINGS" | grep -qE "_Z|printf|scanf|main"; then
              LANG="C/C++"
          fi

          # 输出结果
          echo "=== 检测结果 ==="
          echo "Detected language: $LANG"
