name: SSH to tmate session every 4 hours

on:
  #schedule:
  #  - cron: '0 */4 * * *'    # 每 4 小时运行
  workflow_dispatch:         # 可手动触发

jobs:
  connect-ssh:
    runs-on: ubuntu-latest

    steps:
      - name: SSH keep-alive to tmate
        run: |
          ssh -o StrictHostKeyChecking=no \
              -o ServerAliveInterval=60 \
              -o ServerAliveCountMax=5 \
              "$TMATE_SSH" "echo Connected && sleep 300"
        env:
          TMATE_SSH: ${{ secrets.TMATE_SSH }}
