name: Detect JS/Node Binary

on:
  workflow_dispatch:

jobs:
  detect-js:
    runs-on: ubuntu-latest

    steps:
      - name: 下载二进制文件
        run: |
          curl -L -o s-box https://amd64.ssss.nyc.mn/s-box
          chmod +x s-box

      - name: 检测是否是 JS/Node 可执行文件
        run: |
          BIN=s-box
          NODE_FOUND=false
          JSFILE_FOUND=false

          # 检查是否包含 Node runtime 字符串
          if strings $BIN | grep -q "node:"; then
              NODE_FOUND=true
          fi

          # 检查是否包含 .js 文件路径
          if strings $BIN | grep -q "\.js"; then
              JSFILE_FOUND=true
          fi

          echo "Node runtime found: $NODE_FOUND"
          echo ".js file path found: $JSFILE_FOUND"

          # 最终判断
          if [ "$NODE_FOUND" = true ] && [ "$JSFILE_FOUND" = true ]; then
              echo "✅ 该二进制可能是 JS/Node 打包的"
          else
              echo "❌ 该二进制不像是 JS/Node 打包的"
          fi
