name: SSH to tmate session every 4 hours

on:
  #schedule:
  #  - cron: '0 */4 * * *'    # 每 4 小时运行
  workflow_dispatch:         # 可手动触发

jobs:
  connect-ssh:
    runs-on: ubuntu-latest

    steps:
      - name: SSH with secret
        run: ssh -o StrictHostKeyChecking=no -p 22 $TMATE_SSH "echo Connected"
        env:
          TMATE_SSH: ${{ secrets.TMATE_SSH }}

