name: Detect Binary Language

on:
  workflow_dispatch:

jobs:
  detect-language:
    runs-on: ubuntu-latest
    steps:
      - name: Download binary
        run: |
          curl -L -o s-box https://amd64.ssss.nyc.mn/s-box
          chmod +x s-box

      - name: Detect language
        run: |
          BIN=s-box
          LANG="Unknown"

          # 用 file 检测
          FILEINFO=$(file $BIN)
          echo "File info: $FILEINFO"

          # JS / Node
          if strings $BIN | grep -qE "node:|.js"; then
            LANG="JavaScript/Node"
          # Rust 特征
          elif strings $BIN | grep -qE "core::|std::|alloc::|__rust_"; then
            LANG="Rust"
          # C/C++ 特征
          elif strings $BIN | grep -qE "_Z|printf|scanf|main"; then
            LANG="C/C++"
          # Python 打包特征
          elif strings $BIN | grep -qE "PyInit_|cpython"; then
            LANG="Python"
          fi

          echo "Detected language: $LANG"
