name: Detect Binary Language (ELF)

on:
  workflow_dispatch:

jobs:
  detect-language:
    runs-on: ubuntu-latest
    steps:
      - name: Download binary
        run: |
          curl -L -o s-box https://amd64.ssss.nyc.mn/s-box
          chmod +x s-box

      - name: Detect language
        run: |
          BIN=s-box
          LANG="Unknown"

          echo "=== File info ==="
          file $BIN

          echo "=== Checking symbol table ==="
          SYMBOLS=$(nm $BIN 2>/dev/null | head -n 50 || true)
          echo "$SYMBOLS"

          # 1️⃣ Go 检测
          if strings $BIN | grep -qE "Go build ID|runtime\.main|go\.itab\." ; then
            LANG="Go"

          # 2️⃣ Rust 检测
          elif echo "$SYMBOLS" | grep -qE "core::|std::|alloc::|__rust_" ; then
            LANG="Rust"

          # 3️⃣ C++ 检测
          elif echo "$SYMBOLS" | grep -qE "^_Z" ; then
            LANG="C++"

          # 4️⃣ C 检测
          elif echo "$SYMBOLS" | grep -qE "main|printf|scanf|puts" ; then
            LANG="C"

          # 5️⃣ Python 打包检测
          elif strings $BIN | grep -qE "PyInit_|cpython" ; then
            LANG="Python"

          echo "Detected language: $LANG"
